# Generated by Django 5.1.15 on 2026-05-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KSeFConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=10, unique=True, verbose_name='NIP firmy')),
                ('environment', models.CharField(choices=[('test', 'Testowe'), ('prod', 'Produkcyjne')], default='test', max_length=4, verbose_name='Środowisko')),
                ('token_encrypted', models.TextField(blank=True, verbose_name='Token API (zaszyfrowany)')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Ważność tokena')),
                ('sync_interval_hours', models.PositiveIntegerField(default=6, verbose_name='Interwał synchronizacji (godz.)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia synchronizacja')),
                ('last_sync_reference_number', models.CharField(blank=True, max_length=255, verbose_name='Ostatni numer referencyjny (kursor)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfiguracja KSeF',
                'verbose_name_plural': 'Konfiguracja KSeF',
            },
        ),
        migrations.CreateModel(
            name='KSeFSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Rozpoczęto')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Zakończono')),
                ('status', models.CharField(choices=[('running', 'W toku'), ('success', 'Sukces'), ('error', 'Błąd')], default='running', max_length=10)),
                ('invoices_fetched', models.IntegerField(default=0, verbose_name='Pobrano faktur')),
                ('invoices_new', models.IntegerField(default=0, verbose_name='Nowych faktur')),
                ('error_message', models.TextField(blank=True, verbose_name='Komunikat błędu')),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Log synchronizacji KSeF',
                'verbose_name_plural': 'Logi synchronizacji KSeF',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['started_at'], name='ksef_ksefsy_started_cf4a31_idx')],
            },
        ),
    ]
