# Generated by Django 5.1.15 on 2026-05-11 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Powiadomienia włączone')),
                ('telegram_bot_token_encrypted', models.TextField(blank=True, verbose_name='Token bota Telegram (zaszyfrowany)')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, verbose_name='Chat ID')),
                ('quiet_from', models.TimeField(default=datetime.time(22, 0), verbose_name='Cisza nocna — od')),
                ('quiet_to', models.TimeField(default=datetime.time(8, 0), verbose_name='Cisza nocna — do')),
                ('digest_time', models.TimeField(default=datetime.time(8, 0), verbose_name='Godzina porannego digesty')),
            ],
            options={
                'verbose_name': 'Konfiguracja powiadomień',
            },
        ),
        migrations.CreateModel(
            name='PendingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Czas zdarzenia')),
                ('invoice_count', models.IntegerField(verbose_name='Liczba faktur')),
                ('summary', models.TextField(verbose_name='Treść powiadomienia')),
                ('sent', models.BooleanField(default=False, verbose_name='Wysłane')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Czas wysyłki')),
            ],
            options={
                'verbose_name': 'Oczekujące powiadomienie',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='ksefconfig',
            name='sync_enabled',
            field=models.BooleanField(default=True, verbose_name='Synchronizacja włączona'),
        ),
        migrations.AddField(
            model_name='ksefconfig',
            name='sync_window_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Okno sync — do'),
        ),
        migrations.AddField(
            model_name='ksefconfig',
            name='sync_window_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Okno sync — od'),
        ),
    ]
