# Generated by Django 5.2.14 on 2026-05-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_customuser_company'),
        ('ksef', '0003_ksefsynclog_cancel_requested_ksefsynclog_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksefconfig',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ksef_config', to='accounts.company', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='ksefsynclog',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='accounts.company', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_config', to='accounts.company', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='pendingnotification',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_notifications', to='accounts.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='ksefsynclog',
            name='status',
            field=models.CharField(choices=[('running', 'W toku'), ('success', 'Sukces'), ('error', 'Błąd'), ('cancelled', 'Anulowano')], default='running', max_length=10),
        ),
    ]
