# Generated by Django 5.2.14 on 2026-05-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('viewer', 'Przeglądający'), ('accountant', 'Księgowy'), ('approver', 'Akceptujący płatności'), ('admin', 'Administrator firmy'), ('super_admin', 'Super administrator')], default='viewer', max_length=20, verbose_name='Rola'),
        ),
    ]
