# Generated by Django 5.2.14 on 2026-05-14 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_super_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Darmowy'), ('standard', 'Standard'), ('ultra', 'Ultra')], default='free', max_length=20, verbose_name='Plan')),
                ('valid_from', models.DateField(verbose_name='Ważna od')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Ważna do')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('store_platform', models.CharField(blank=True, max_length=20, verbose_name='Platforma sklepu')),
                ('store_purchase_token', models.TextField(blank=True, verbose_name='Token zakupu')),
                ('store_subscription_id', models.CharField(blank=True, max_length=255, verbose_name='ID subskrypcji')),
                ('store_last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia weryfikacja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='accounts.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Licencja',
                'verbose_name_plural': 'Licencje',
            },
        ),
    ]
