# Generated by Django 5.2.14 on 2026-05-14 06:43

import datetime
from django.db import migrations


def create_licenses(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    CompanyLicense = apps.get_model('accounts', 'CompanyLicense')
    today = datetime.date.today()
    for company in Company.objects.all():
        CompanyLicense.objects.get_or_create(
            company=company,
            defaults={'plan': 'free', 'valid_from': today},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_companylicense'),
    ]

    operations = [
        migrations.RunPython(create_licenses, migrations.RunPython.noop),
    ]
