# Generated by Django 5.2.14 on 2026-06-08 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_company_licenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=34, verbose_name='Numer rachunku (NRB)')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Etykieta')),
                ('is_default', models.BooleanField(default=False, verbose_name='Domyślny')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='Bank')),
                ('bank_key', models.CharField(blank=True, max_length=20, verbose_name='Klucz banku')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Rachunek bankowy',
                'verbose_name_plural': 'Rachunki bankowe',
                'ordering': ['-is_default', 'label'],
            },
        ),
    ]
