# Generated by Django 5.2.14 on 2026-06-08 09:06

from django.db import migrations


def migrate_bank_accounts(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    CompanyBankAccount = apps.get_model('accounts', 'CompanyBankAccount')
    for company in Company.objects.exclude(bank_account=''):
        if not CompanyBankAccount.objects.filter(company=company).exists():
            CompanyBankAccount.objects.create(
                company=company,
                account_number=company.bank_account,
                label='Rachunek główny',
                is_default=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_companybankaccount'),
    ]

    operations = [
        migrations.RunPython(migrate_bank_accounts, migrations.RunPython.noop),
    ]
