# Override dla lokalnego developmentu — hot-reload, bez portu bazy (możliwy konflikt)
services:
  web:
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: []

  celery:
    volumes:
      - .:/app

  celery-beat:
    volumes:
      - .:/app
