# Generated by Django 5.1.15 on 2026-05-11 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invoice_status', 'Zmiana statusu faktury'), ('invoice_note', 'Notatka faktury'), ('payment_file', 'Generowanie przelewów'), ('bank_upload', 'Import wyciągu bankowego'), ('bank_confirm', 'Zatwierdzenie wyciągu'), ('bank_match', 'Dopasowanie transakcji'), ('ksef_sync', 'Synchronizacja KSeF'), ('ksef_config', 'Konfiguracja KSeF'), ('user_create', 'Utworzenie użytkownika'), ('user_modify', 'Modyfikacja użytkownika'), ('user_delete', 'Usunięcie użytkownika'), ('login', 'Logowanie'), ('logout', 'Wylogowanie')], db_index=True, max_length=30, verbose_name='Akcja')),
                ('entity_type', models.CharField(blank=True, max_length=50, verbose_name='Typ obiektu')),
                ('entity_id', models.CharField(blank=True, max_length=50, verbose_name='ID obiektu')),
                ('entity_repr', models.CharField(blank=True, max_length=255, verbose_name='Opis obiektu')),
                ('detail', models.JSONField(default=dict, verbose_name='Szczegóły')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Czas')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Log audytu',
                'verbose_name_plural': 'Logi audytu',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='core_auditl_action_096de0_idx'), models.Index(fields=['actor', 'timestamp'], name='core_auditl_actor_i_19c60f_idx')],
            },
        ),
    ]
