# Generated by Django 5.1.15 on 2026-05-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ksef_reference_number', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Numer referencyjny KSeF')),
                ('invoice_number', models.CharField(db_index=True, max_length=64, verbose_name='Numer faktury')),
                ('seller_name', models.CharField(max_length=255, verbose_name='Nazwa sprzedawcy')),
                ('seller_nip', models.CharField(db_index=True, max_length=10, verbose_name='NIP sprzedawcy')),
                ('seller_address', models.TextField(blank=True, verbose_name='Adres sprzedawcy')),
                ('buyer_nip', models.CharField(max_length=10, verbose_name='NIP nabywcy')),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kwota netto')),
                ('amount_vat', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kwota VAT')),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kwota brutto')),
                ('currency', models.CharField(default='PLN', max_length=3, verbose_name='Waluta')),
                ('is_split_payment', models.BooleanField(default=False, verbose_name='Mechanizm podzielonej płatności')),
                ('vat_amount_split', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Kwota VAT (split payment)')),
                ('issue_date', models.DateField(db_index=True, verbose_name='Data wystawienia')),
                ('payment_due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Termin płatności')),
                ('bank_account_number', models.CharField(blank=True, max_length=34, verbose_name='Numer rachunku bankowego sprzedawcy (NRB)')),
                ('payment_title', models.CharField(blank=True, max_length=255, verbose_name='Tytuł płatności')),
                ('status', models.CharField(choices=[('nowa', 'Nowa'), ('sporna', 'Sporna'), ('zaakceptowana', 'Zaakceptowana'), ('przekazano_do_oplacenia', 'Przekazano do opłacenia'), ('oplacona', 'Opłacona')], db_index=True, default='nowa', max_length=30, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('raw_xml', models.TextField(blank=True, verbose_name='Surowy XML FA(2)')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Data synchronizacji')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizowane przez')),
            ],
            options={
                'verbose_name': 'Faktura kosztowa',
                'verbose_name_plural': 'Faktury kosztowe',
                'ordering': ['-issue_date', '-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30, verbose_name='Poprzedni status')),
                ('new_status', models.CharField(max_length=30, verbose_name='Nowy status')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zmiany')),
                ('note', models.TextField(blank=True, verbose_name='Notatka')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Zmienione przez')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='invoices.invoice', verbose_name='Faktura')),
            ],
            options={
                'verbose_name': 'Log statusu faktury',
                'verbose_name_plural': 'Logi statusów faktur',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issue_date'], name='invoices_in_status_34c4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['seller_nip', 'status'], name='invoices_in_seller__5e6dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_due_date', 'status'], name='invoices_in_payment_c2699e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='invoices_in_issue_d_588fba_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicestatuslog',
            index=models.Index(fields=['invoice', 'changed_at'], name='invoices_in_invoice_1132eb_idx'),
        ),
    ]
