# Generated by Django 5.2.14 on 2026-05-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_customuser_company'),
        ('invoices', '0003_add_payment_date_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ksef_reference_number',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Numer referencyjny KSeF'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='raw_xml',
            field=models.TextField(blank=True, verbose_name='Surowy XML FA(2)/FA(3)'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('ksef_reference_number', 'company')},
        ),
    ]
