# Generated by Django 5.1.15 on 2026-05-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nazwa pliku')),
                ('account_number', models.CharField(blank=True, max_length=34, verbose_name='Numer rachunku')),
                ('statement_date', models.DateField(blank=True, null=True, verbose_name='Data wyciągu')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje na przegląd'), ('reviewed', 'W przeglądzie'), ('confirmed', 'Zatwierdzony')], default='pending', max_length=10)),
                ('raw_content', models.TextField(verbose_name='Surowa treść MT940')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wgrania')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zatwierdzenia')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_statements', to=settings.AUTH_USER_MODEL, verbose_name='Zatwierdzony przez')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_statements', to=settings.AUTH_USER_MODEL, verbose_name='Wgrany przez')),
            ],
            options={
                'verbose_name': 'Wyciąg bankowy',
                'verbose_name_plural': 'Wyciągi bankowe',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Data transakcji')),
                ('value_date', models.DateField(verbose_name='Data waluty')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kwota')),
                ('currency', models.CharField(default='PLN', max_length=3, verbose_name='Waluta')),
                ('is_debit', models.BooleanField(verbose_name='Uznanie (D) / Obciążenie (C)')),
                ('description', models.TextField(blank=True, verbose_name='Opis transakcji')),
                ('reference', models.CharField(blank=True, max_length=35, verbose_name='Referencja')),
                ('is_matched', models.BooleanField(default=False, verbose_name='Dopasowana')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_statements.bankstatement', verbose_name='Wyciąg')),
            ],
            options={
                'verbose_name': 'Transakcja bankowa',
                'verbose_name_plural': 'Transakcje bankowe',
            },
        ),
        migrations.CreateModel(
            name='TransactionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('amount', 'Kwota'), ('nip', 'NIP w tytule'), ('invoice_nr', 'Numer faktury'), ('manual', 'Ręczne')], max_length=15)),
                ('confidence', models.CharField(choices=[('high', 'Pewne'), ('medium', 'Możliwe'), ('low', 'Niepewne')], max_length=10)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Potwierdzone')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Potwierdzone przez')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='invoices.invoice', verbose_name='Faktura')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='bank_statements.banktransaction', verbose_name='Transakcja')),
            ],
            options={
                'verbose_name': 'Dopasowanie transakcji',
                'verbose_name_plural': 'Dopasowania transakcji',
            },
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['statement', 'transaction_date'], name='bank_statem_stateme_ea165a_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['amount', 'is_matched'], name='bank_statem_amount_15c63a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionmatch',
            unique_together={('transaction', 'invoice')},
        ),
    ]
