# Generated by Django 5.2.14 on 2026-05-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_customuser_company'),
        ('bank_statements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Firma'),
        ),
    ]
