# Generated by Django 5.2.15 on 2026-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statements', '0002_add_company_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='file_format',
            field=models.CharField(default='mt940', max_length=20, verbose_name='Format pliku'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='raw_content',
            field=models.TextField(verbose_name='Surowa treść pliku'),
        ),
    ]
