# Generated by Django 5.2.15 on 2026-06-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statements', '0003_add_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='counterparty',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nadawca/Odbiorca'),
        ),
    ]
