# Generated by Django 5.1.15 on 2026-05-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('erste', 'Erste Bank (.txt)'), ('elixir', 'Elixir-0 (.pli)')], max_length=10, verbose_name='Format pliku')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nazwa pliku')),
                ('file_content', models.BinaryField(verbose_name='Zawartość pliku')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Suma brutto')),
                ('invoice_count', models.IntegerField(verbose_name='Liczba faktur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data generacji')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Wygenerowane przez')),
            ],
            options={
                'verbose_name': 'Plik przelewów',
                'verbose_name_plural': 'Pliki przelewów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentFileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kwota')),
                ('line_number', models.PositiveIntegerField(verbose_name='Numer linii w pliku')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_items', to='invoices.invoice', verbose_name='Faktura')),
                ('payment_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.paymentfile', verbose_name='Plik przelewów')),
            ],
            options={
                'verbose_name': 'Pozycja pliku przelewów',
                'verbose_name_plural': 'Pozycje pliku przelewów',
                'ordering': ['line_number'],
                'unique_together': {('payment_file', 'invoice')},
            },
        ),
    ]
