# Generated by Django 5.2.14 on 2026-06-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_company_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentfile',
            name='debit_account',
            field=models.CharField(blank=True, max_length=34, verbose_name='Rachunek obciążeniowy'),
        ),
        migrations.AddField(
            model_name='paymentfileitem',
            name='debit_account',
            field=models.CharField(blank=True, max_length=34, verbose_name='Rachunek obciążeniowy'),
        ),
        migrations.AlterField(
            model_name='paymentfile',
            name='format',
            field=models.CharField(choices=[('erste', 'Erste Bank (.txt)'), ('mbank', 'mBank (.txt)'), ('elixir', 'Elixir-0 (.pli)')], max_length=10, verbose_name='Format pliku'),
        ),
    ]
