# Generated by Django 5.2.14 on 2026-06-08 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_migrate_company_bank_account'),
        ('outgoing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=10, verbose_name='NIP')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='accounts.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Nabywca',
                'verbose_name_plural': 'Nabywcy',
                'ordering': ['name'],
                'unique_together': {('company', 'nip')},
            },
        ),
        migrations.AddField(
            model_name='outgoinginvoice',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='outgoing.buyer', verbose_name='Nabywca'),
        ),
    ]
